<?php

namespace AppBundle\Repository;

/**
 * EpreuveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpreuveRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEpreuve()
	{
		$epreuve = $this->createQueryBuilder('epreuve');

		$epreuve->select('epreuve.id',
					  'epreuve.titre',
					  'epreuve.description',
					  'epreuve.path')
		;
		return $epreuve->getQuery()->getSingleResult();
	}
}
